### ISSUE TITLE
Wiki points to bad link

### ISSUE THREAD

**Issue by treeplate** [TodePond/DreamBerd---e-acc#359]
The [examples](example.com) link points to the DreamBerd repo, which has no such `Examples.md`. I would add a PR but it appears that option is not available for wikis.

**Comment by TodePond** [comment]
Thanks for the heads up. If you find the examples, please let me know the correct link and I'll update it :)

**Comment by treeplate** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/blob/main/LICENSE.md

**Comment by treeplate** [comment]
the wiki now points to a valid link, closing repo
